train:
    seed: 2
    batch_size: 256
    n_epochs: 500
    val_interval: 50
    num_workers: 25
    drop_last: false
    base_path: 'data/sleep-edfx'
    output_dir: 'outputs/fnirs'
    run_dir: 'aekl_eeg_fnirs'
    experiment: 'AEKL'
models:
  optimizer_g_lr: 0.005 #Mexer, menor 10E-4
  optimizer_d_lr: 0.0005 #Maior que o anterior 
  adv_weight: 0.01  #
  kl_weight: 1E-9   #
  spectral_weight: 1E4 # testando 1e4, era 1e6

autoencoderkl:
  params:
    spatial_dims: 1
    in_channels: 52
    out_channels: 52
    num_res_blocks: [2, 2, 2]  # Original 3-level architecture
    num_channels: [32, 64, 64]  # Original channel configuration
    latent_channels: 64
    norm_num_groups: 4
    attention_levels: [False, False, False]
    with_encoder_nonlocal_attn: false
    with_decoder_nonlocal_attn: false

patchdiscriminator:
  params:
    spatial_dims: 1
    num_layers_d: 3
    num_channels: 64
    in_channels: 52
    out_channels: 52
    kernel_size: 3
    norm: "BATCH"
    bias: false
    padding: 1

unet:
  params:
    image_size: 750
    in_channels: 1
    out_channels: 1
    model_channels: 64
    attention_resolutions: [8,4]
    num_res_blocks: 2
    channel_mult: [1,2]
    dropout: 0.0
    conv_resample: True
    num_heads: 1
    use_scale_shift_norm: False
    resblock_updown: True

#latent_channels: 1 # Talvez trocar para 3